/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as Price_plansRouteImport } from './routes/price_plans'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as IndexRouteImport } from './routes/index'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const Price_plansRoute = Price_plansRouteImport.update({
  id: '/price_plans',
  path: '/price_plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages': typeof PagesRoute
  '/price_plans': typeof Price_plansRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages': typeof PagesRoute
  '/price_plans': typeof Price_plansRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pages': typeof PagesRoute
  '/price_plans': typeof Price_plansRoute
  '/products': typeof ProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pages' | '/price_plans' | '/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pages' | '/price_plans' | '/products'
  id: '__root__' | '/' | '/pages' | '/price_plans' | '/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesRoute: typeof PagesRoute
  Price_plansRoute: typeof Price_plansRoute
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price_plans': {
      id: '/price_plans'
      path: '/price_plans'
      fullPath: '/price_plans'
      preLoaderRoute: typeof Price_plansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesRoute: PagesRoute,
  Price_plansRoute: Price_plansRoute,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
